doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '15'
                url: "%env(resolve:DATABASE_URL)%"
                driver: "pdo_mysql"
#                server_version: "8.0.35"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            errolda:
                schema_filter: ~^.*$~
                driver: "%env(resolve:ERROLDA_DATABASE_DRIVER)%"
                host: "%env(resolve:ERROLDA_DATABASE_HOST)%"
                port: "%env(resolve:ERROLDA_DATABASE_PORT)%"
                dbname: "%env(resolve:ERROLDA_DATABASE_NAME)%"
                user: "%env(resolve:ERROLDA_DATABASE_USER)%"
                password: "%env(resolve:ERROLDA_DATABASE_PASSWORD)%"
                charset: "WE8MSWIN1252"

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        # VERY IMPORTANT: When there are more than one entity managers, they had to be in separate directories they can't be parent and child. 
        # Make a Default directory instead o using Entity directory 
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Default"
                        prefix: 'App\Entity\Default'
            errolda:
                connection: errolda
                mappings:
                    Errolda:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/Errolda"
                        prefix: 'App\Entity\Errolda'
                        alias: "Errolda"
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
